import './globals.scss'
import type { Metadata } from 'next'
import Providers from '@/components/Providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body >
          {children}
        </body>
      </Providers>
    </html>
  )
}
